[build]
  base = "./user-interface"          # user-interface directory
  publish = "build"            # Build output directory
  command = "npm run build"    # Build command
  
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
