[build]
  base = "./frontend"          # Frontend directory
  publish = "build"            # Build output directory
  command = "npm run build"    # Build command
  functions = "backend/netlify/functions"


[functions]
  directory = "backend/netlify/functions"  # Directory for Netlify functions
  node_bundler = "esbuild"                 # Use esbuild for bundling functions

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
